QUESTION_GOAL = 1500
QUESTION_POINTS_MAX = 35.0
ACCURACY_FLOOR = 40.0
ACCURACY_CEILING = 80.0
ACCURACY_POINTS_MAX = 30.0
COMPLETED_SESSION_POINTS = 2.0
COMPLETED_SESSION_POINTS_MAX = 20.0
CONSISTENCY_DAYS_WINDOW = 30
CONSISTENCY_POINTS_PER_DAY = 0.5
CONSISTENCY_POINTS_MAX = 15.0
SUBCATEGORY_INSIGHT_MIN_ATTEMPTS = 3
SUBCATEGORY_ATTENTION_ACCURACY_THRESHOLD = 60.0

LEVEL_THRESHOLDS = (
    (80.0, 'Academico Avancado'),
    (60.0, 'Avancado'),
    (40.0, 'Dedicado'),
    (20.0, 'Em Evolucao'),
    (0.0, 'Iniciante'),
)
