CONSISTENCY_DAYS_WINDOW = 30

PROGRESS_DISCIPLINE_GOAL = 4
PROGRESS_DISCIPLINE_POINTS_MAX = 10.0
PROGRESS_QUESTION_COVERAGE_POINTS_MAX = 55.0
PROGRESS_SESSION_GOAL = 12
PROGRESS_SESSION_POINTS_MAX = 15.0
PROGRESS_ACCURACY_FLOOR = 55.0
PROGRESS_ACCURACY_CEILING = 85.0
PROGRESS_ACCURACY_POINTS_MAX = 20.0
PROGRESS_ACCURACY_SAMPLE_SIZE = 80

SCORE_RECENT_ACCURACY_WINDOW_DAYS = 21
SCORE_SIMULATION_WINDOW_DAYS = 21
SCORE_CONSISTENCY_WINDOW_DAYS = 14
INACTIVITY_GRACE_DAYS = 1
SCORE_INACTIVITY_PENALTY_PER_DAY = 1.0
SCORE_INACTIVITY_PENALTY_MAX = 100.0

RECENT_INDEX_ATTEMPT_SAMPLE_SIZE = 24
RECENT_INDEX_ATTEMPT_DECAY = 0.94
RECENT_INDEX_ATTEMPTS_WEIGHT = 0.75
RECENT_INDEX_CONSISTENCY_WEIGHT = 0.15
RECENT_INDEX_SIMULATION_WEIGHT = 0.10
RECENT_INDEX_ACTIVE_DAYS_GOAL = 7
RECENT_INDEX_SESSION_GOAL = 2

SUBCATEGORY_INSIGHT_MIN_ATTEMPTS = 3
SUBCATEGORY_ATTENTION_ACCURACY_THRESHOLD = 60.0

LEVEL_THRESHOLDS = (
    (80.0, 'Academico Avancado'),
    (60.0, 'Avancado'),
    (40.0, 'Dedicado'),
    (20.0, 'Em Evolucao'),
    (0.0, 'Iniciante'),
)
