CONSISTENCY_DAYS_WINDOW = 30

PROGRESS_DISCIPLINE_GOAL = 4
PROGRESS_DISCIPLINE_POINTS_MAX = 10.0
PROGRESS_QUESTION_COVERAGE_POINTS_MAX = 55.0
PROGRESS_SESSION_GOAL = 12
PROGRESS_SESSION_POINTS_MAX = 15.0
PROGRESS_ACCURACY_FLOOR = 55.0
PROGRESS_ACCURACY_CEILING = 85.0
PROGRESS_ACCURACY_POINTS_MAX = 20.0
PROGRESS_ACCURACY_SAMPLE_SIZE = 80

SCORE_RECENT_ATTEMPTS_WINDOW_DAYS = 7
SCORE_RECENT_ACCURACY_WINDOW_DAYS = 21
SCORE_SIMULATION_WINDOW_DAYS = 21
SCORE_SESSION_MOMENTUM_WINDOW_DAYS = 21
SCORE_CONSISTENCY_WINDOW_DAYS = 14

MOMENTUM_ATTEMPTS_GOAL = 40
MOMENTUM_ATTEMPTS_POINTS_ABS = 2.0
MOMENTUM_ACTIVE_DAYS_GOAL = 7
MOMENTUM_ACTIVE_DAYS_POINTS_ABS = 3.0
MOMENTUM_ACCURACY_FLOOR = 40.0
MOMENTUM_ACCURACY_CEILING = 85.0
MOMENTUM_ACCURACY_POINTS_ABS = 3.0
MOMENTUM_ACCURACY_SAMPLE_SIZE = 20
MOMENTUM_SIMULATION_GOAL = 2
MOMENTUM_SIMULATION_POINTS_MAX = 1.0
MOMENTUM_STREAK_CAP = 5
MOMENTUM_STREAK_POINTS_MAX = 1.0
MOMENTUM_SESSION_DELTA_NEUTRAL = 3.0
MOMENTUM_SESSION_DELTA_FOR_MAX = 12.0
MOMENTUM_SESSION_POINTS_ABS = 4.0
INACTIVITY_GRACE_DAYS = 1
SCORE_INACTIVITY_PENALTY_PER_DAY = 1.0
SCORE_INACTIVITY_PENALTY_MAX = 100.0
MOMENTUM_INACTIVITY_PENALTY_PER_DAY = 0.2
MOMENTUM_INACTIVITY_PENALTY_MAX = 20.0

SUBCATEGORY_INSIGHT_MIN_ATTEMPTS = 3
SUBCATEGORY_ATTENTION_ACCURACY_THRESHOLD = 60.0

LEVEL_THRESHOLDS = (
    (80.0, 'Academico Avancado'),
    (60.0, 'Avancado'),
    (40.0, 'Dedicado'),
    (20.0, 'Em Evolucao'),
    (0.0, 'Iniciante'),
)
